# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1

      - name: npm dependencies
        run: npm install

      - name: Test
        run: npm run test

      - name: Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          token: bbf3a02f-7788-43a3-aaa5-e435c1b1d648
          file: coverage
